version: '2'
services:
    slon-app:
        image: slon
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://slon-postgresql:5432/slon
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080 #the listening port
    slon-postgresql:
        extends:
            file: postgresql.yml
            service: slon-postgresql
